# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
#消除 警告
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
        end
    end
end
target 'TestTableView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TestTableView

  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
 pod 'Masonry'
  pod 'YYKit'
pod'SDWebImage'

  pod 'ReactiveObjC'
  pod 'AFNetworking', '~> 3.0'


  target 'TestTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestTableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
