# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TestTableView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TestTableView

  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
 	pod 'Masonry'
  pod 'YYKit'


  target 'TestTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestTableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
